### PR TITLE
Implement Aeolus and Siren

### PR DESCRIPTION
**Pull request by bs24**
Still an issue with the UI supposed to display token information

### CODE REVIEW

**Comment by quietmint** [comment]
Choosing the direction of the wind token is very confusing. It's not clear to me which way the wind will blow if I click on a space -- am I choosing the direction the wind will blow to or from? Instead of a red square, we need to show a picture of the wind token in the correct orientation. Also, the positioning of the red square seems off. The bottom-left spot looks correct, but the other spots overlap with real spaces on the board, which looks bizarre.

After the token is placed, I expect it to appear in the same spot that I clicked. For example, if I click on the bottom-left corner near the space "A1", I expect the wind token to appear in that position. Instead, the token gets added to the opposite corner of the board.

We need to do some extra calculations in board.js if we want to position the wind token "outside the board" but still use x,y,z coords. It probably makes more sense to manually position the wind token and not use x,y,z for it at all?

The log message and player panel for the wind token also confuse me. "Aeolus: quietmint0 places the Wind Token (-> A1)" should give the direction name ("north", "southwest", etc.) instead of a space on the board.

**Comment by bs24** [comment]
The offset for the positioning in your build is strange indeed, I did not have it on mine... just having x,y in -1,+5 and board.js's xCenters, zCenters seemed to work

For the other issues, I am not sure how to solve them. A semi-opaque token might be good indeed. For the direction, we need to have a north arrow on the board with your idea I guess? For the position, I tried to follow the rules, by just rotating the token rather than moving it, but I understand your point

**Comment by quietmint** [comment]
My original idea (before seeing how you did this) was to not use the board at all. I was thinking of displaying the token in the top right corner as a flat image (like Golden Fleece or Nyx Night Power). To choose the direction, I was thinking of a pop-up dialog like Atlas (choose block vs. dome).

The advantage of attaching it to the 3D board is the token rotates automatically. Probably this is better overall than my first idea if we can improve the placement/position.

**Comment by bs24** [comment]
Also, placing the token on a selectable space will be weird if the other token (Siren vs Aeolus) is in place, so that was one reason to place the token outside a selectable space. Did you update script/board.js as it seems that the offset you have should be corrected by the update in this file?

**Comment by bs24** [comment]
I improved the visual effects / the log. Seems that all your comments are now addressed except:
- the offset in the position which I cannot reproduce (board.js l39-40 is supposed to modify it)
- the fact that the token appears always at the same position and not where the user clicked: I think we cannot really do it for Aeolus vs Siren as both tokens may end up on the same place. I guess this otherwise a subjective opinion, so I personally prefer the current version, but understand your point.

**Comment by quietmint** [comment]
Siren: Something is wrong with the initial setup. I chose Siren + Urania and set Urania as the first player. Siren was never given a chance to place the Arrow Token. Urania can take a normal turn, but Siren's turn fails (of course, because it looks for the Arrow Token which does not exist)
image

**Comment by bs24** [comment]
I don't understand how this can happen. The santorini.game.php and Siren class files are supposed to enforce it. I cannot reproduce it on my studio version (santorinigretirse)

**Pull request merged**
